FROM python:3.8.3-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

# install psycopg2 dependencies
#https://stackoverflow.com/questions/35736598/cannot-pip-install-cryptography-in-docker-alpine-linux-3-3-with-openssl-1-0-2g
#https://stackoverflow.com/questions/59441794/error-could-not-build-wheels-for-cryptography-which-use-pep-517-and-cannot-be-i
RUN apk update
RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo
RUN apk add postgresql-dev gcc python3-dev musl-dev zlib zlib-dev jpeg-dev


# install dependencies
RUN pip install --upgrade pip
#RUN pip install --upgrade pip setuptools wheel
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r /usr/src/app/requirements.txt

COPY . /usr/src/app
