SECRET_KEY = ''

DEBUG = True

OAUTH_GOOGLE_CLIENT_ID = ''
OAUTH_GOOGLE_SECRET = ''
OAUTH_GOOGLE_KEY = ''

EMAIL_BACKEND = ''
EMAIL_HOST = ""
EMAIL_PORT = 465
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_SSL = True

TWILIO_SID = ''
TWILIO_TOKEN = ''
TWILIO_FROM_NUMBER = ''

REDIS_CACHE_LOCATION = ''

CELERY_BROKER_URL = ''
CELERY_RESULT_BACKEND = ''

CHANNEL_REDIS_HOST = ''
CHANNEL_REDIS_SECRET_KEY = ''

SQL_ENGINE=''
POSTGRES_DB = ''
POSTGRES_USER = ''
POSTGRES_PASSWORD = ''
POSTGRES_HOSTe = ''
POSTGRES_HOST = ''
POSTGRES_PORT = ''

SENTRY_DSN = ""