# Generated by Django 3.1.7 on 2021-03-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='author',
            new_name='id_author',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='category',
            new_name='id_category',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='annual_return',
            field=models.FloatField(default=0),
        ),
    ]
