# Generated by Django 3.1.7 on 2021-03-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210327_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='min_nav',
            field=models.IntegerField(default=1, verbose_name='Минимальный СЧА'),
            preserve_default=False,
        ),
    ]
