# Generated by Django 3.1.7 on 2021-04-01 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_strategy_min_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='annual_return',
            field=models.FloatField(default=0, verbose_name='Годовая доходность'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='date_create',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.CharField(max_length=2056, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.strategyauthor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.strategycategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
