# Generated by Django 3.1.7 on 2021-04-08 20:29

from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210401_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='pic_yield',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='pics/', verbose_name='График доходности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='date_modify',
            field=models.DateField(verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
