# Generated by Django 3.1.7 on 2021-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='pic_yield',
            field=models.ImageField(blank=True, upload_to='pics/', verbose_name='График доходности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='date_modify',
            field=models.DateField(verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
