# Generated by Django 3.1.7 on 2021-04-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210409_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategytag',
            options={'ordering': ['name'], 'verbose_name': 'Тег для стратегий', 'verbose_name_plural': 'Теги для стратегий'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['name'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='main.Subscription', verbose_name='Подписки'),
        ),
    ]
