# Generated by Django 3.1.7 on 2021-04-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210403_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
