# Generated by Django 3.1.7 on 2021-04-03 18:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='pic_yield',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='pics/', verbose_name='График доходности'),
        ),
    ]
