# Generated by Django 3.1.7 on 2021-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210414_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
