# Generated by Django 3.1.7 on 2021-04-30 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_strategy_is_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Архивная стратегия'),
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='tags',
        ),
        migrations.AddField(
            model_name='strategy',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), blank=True, default='{default}', size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StrategyTag',
        ),
    ]
