# Generated by Django 3.1.7 on 2021-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210430_1750'),
    ]

    sql = """
    create VIEW StrategyView AS
      SELECT s.id, s.title, sc.name category_name, sa.first_name || ' '|| sa.last_name
 	  as author_name 
	  from main_strategy s
	  left join main_strategycategory sc on (s.id_category_id=sc.id)
	  left join main_strategyauthor sa on (s.id_author_id=sa.id)
    """

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS StrategyView ;'),
        migrations.RunSQL(sql)
    ]
